"""add is_synthetic flag to policy and accident_claim

Revision ID: 13bf4850a2ee
Revises: 5b0daa61ba39
Create Date: 2026-06-01 23:40:31.566115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13bf4850a2ee'
down_revision: Union[str, Sequence[str], None] = '5b0daa61ba39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accident_claim_info', sa.Column('is_synthetic', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('policy_info', sa.Column('is_synthetic', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('policy_info', 'is_synthetic')
    op.drop_column('accident_claim_info', 'is_synthetic')
    # ### end Alembic commands ###
