"""initial: 7 tables

Revision ID: 54e8b4b7c22d
Revises: 
Create Date: 2026-06-01 20:01:51.713876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '54e8b4b7c22d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insuree_info',
    sa.Column('insuree_id', sa.String(length=64), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('occupation', sa.String(length=128), nullable=True),
    sa.Column('marital_status', sa.String(length=32), nullable=True),
    sa.Column('claim_times', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('insuree_id')
    )
    op.create_table('model_info',
    sa.Column('model_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('model_algorithm', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('model_auc', sa.Float(), nullable=True),
    sa.Column('model_f1', sa.Float(), nullable=True),
    sa.Column('model_precision', sa.Float(), nullable=True),
    sa.Column('model_recall', sa.Float(), nullable=True),
    sa.Column('pr_auc', sa.Float(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('feature_count', sa.Integer(), nullable=True),
    sa.Column('cv_f1_mean', sa.Float(), nullable=True),
    sa.Column('cv_f1_std', sa.Float(), nullable=True),
    sa.Column('param_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('train_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('model_file_path', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('model_id')
    )
    op.create_table('user_info',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('user_role', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_info_user_role'), 'user_info', ['user_role'], unique=False)
    op.create_index(op.f('ix_user_info_username'), 'user_info', ['username'], unique=True)
    op.create_table('policy_info',
    sa.Column('policy_id', sa.String(length=64), nullable=False),
    sa.Column('insuree_id', sa.String(length=64), nullable=False),
    sa.Column('insurance_type', sa.String(length=64), nullable=True),
    sa.Column('insurance_amount', sa.Float(), nullable=True),
    sa.Column('premium', sa.Float(), nullable=True),
    sa.Column('insure_date', sa.Date(), nullable=True),
    sa.Column('effect_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['insuree_id'], ['insuree_info.insuree_id'], ),
    sa.PrimaryKeyConstraint('policy_id')
    )
    op.create_index(op.f('ix_policy_info_insuree_id'), 'policy_info', ['insuree_id'], unique=False)
    op.create_table('accident_claim_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('policy_id', sa.String(length=64), nullable=False),
    sa.Column('accident_date', sa.Date(), nullable=True),
    sa.Column('accident_type', sa.String(length=64), nullable=True),
    sa.Column('has_witness', sa.Boolean(), nullable=True),
    sa.Column('claim_amount', sa.Float(), nullable=True),
    sa.Column('claim_date', sa.Date(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('paid_amount', sa.Float(), nullable=True),
    sa.Column('is_fraud', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policy_info.policy_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accident_claim_info_policy_id'), 'accident_claim_info', ['policy_id'], unique=False)
    op.create_table('fraud_detect_result',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('policy_id', sa.String(length=64), nullable=False),
    sa.Column('accident_claim_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('fraud_prob', sa.Float(), nullable=False),
    sa.Column('raw_prob', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('threshold_used', sa.Float(), nullable=True),
    sa.Column('feature_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('shap_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('agent_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('detect_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('manual_result', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accident_claim_id'], ['accident_claim_info.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['model_info.model_id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policy_info.policy_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accident_claim_id')
    )
    op.create_index(op.f('ix_fraud_detect_result_detect_time'), 'fraud_detect_result', ['detect_time'], unique=False)
    op.create_index(op.f('ix_fraud_detect_result_fraud_prob'), 'fraud_detect_result', ['fraud_prob'], unique=False)
    op.create_index(op.f('ix_fraud_detect_result_policy_id'), 'fraud_detect_result', ['policy_id'], unique=False)
    op.create_index(op.f('ix_fraud_detect_result_risk_level'), 'fraud_detect_result', ['risk_level'], unique=False)
    op.create_table('case_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('policy_id', sa.String(length=64), nullable=False),
    sa.Column('detect_result_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('operate_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('manual_result', sa.String(length=32), nullable=True),
    sa.Column('remark', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['detect_result_id'], ['fraud_detect_result.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policy_info.policy_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_info.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_history_policy_id'), 'case_history', ['policy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_history_policy_id'), table_name='case_history')
    op.drop_table('case_history')
    op.drop_index(op.f('ix_fraud_detect_result_risk_level'), table_name='fraud_detect_result')
    op.drop_index(op.f('ix_fraud_detect_result_policy_id'), table_name='fraud_detect_result')
    op.drop_index(op.f('ix_fraud_detect_result_fraud_prob'), table_name='fraud_detect_result')
    op.drop_index(op.f('ix_fraud_detect_result_detect_time'), table_name='fraud_detect_result')
    op.drop_table('fraud_detect_result')
    op.drop_index(op.f('ix_accident_claim_info_policy_id'), table_name='accident_claim_info')
    op.drop_table('accident_claim_info')
    op.drop_index(op.f('ix_policy_info_insuree_id'), table_name='policy_info')
    op.drop_table('policy_info')
    op.drop_index(op.f('ix_user_info_username'), table_name='user_info')
    op.drop_index(op.f('ix_user_info_user_role'), table_name='user_info')
    op.drop_table('user_info')
    op.drop_table('model_info')
    op.drop_table('insuree_info')
    # ### end Alembic commands ###
